#
# Copyright © 2020 ProStore
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.7'

networks:
  dtm-query-execution:

volumes:
  dtmservice:

services:
  dtmservicedb:
    image: mariadb:10.5.3
    container_name: dtmservicedb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dtmservice:/var/lib/mysql
    environment:
      MYSQL_DATABASE: dtmservice
      MYSQL_USER: dtmuser
      MYSQL_PASSWORD: Cat6Gmt7Ncr
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

  zookeeper:
    image: zookeeper:3.6
    container_name: zk-1.dtm.local
    restart: always
    ports:
      - "2181:2181"
